// CelesTrak provides TLE data files directly over HTTPS. 
// This file is for "Space Stations" and contains the ISS (NORAD ID 25544).
const CELESTRAK_URL = "https://celestrak.com/NORAD/elements/stations.txt";
const statusElement = document.getElementById('loading-status');
const epochDateElement = document.getElementById('epoch-date');

/**
 * Main function to fetch the raw TLE text data.
  */
  async function fetchTLEData() {
      statusElement.textContent = "Fetching TLE data from CelesTrak...";
          
              try {
                      const response = await fetch(CELESTRAK_URL);
                              
                                      if (!response.ok) {
                                                  throw new Error(`HTTP error! Status: ${response.status}. Could not reach CelesTrak.`);
                                                          }
                                                                  
                                                                          const rawText = await response.text();
                                                                                  
                                                                                          // Hide the status message and process the data
                                                                                                  statusElement.style.display = 'none';
                                                                                                          processAndVisualizeTLE(rawText); 

                                                                                                              } catch (error) {
                                                                                                                      console.error("Data Fetch Error:", error);
                                                                                                                              statusElement.style.display = 'block';
                                                                                                                                      statusElement.textContent = `Error: ${error.message}`;
                                                                                                                                              statusElement.style.color = 'red';
                                                                                                                                                  }
                                                                                                                                                  }

                                                                                                                                                  /**
                                                                                                                                                   * Parses the raw TLE text to find ISS data and extracts orbital parameters.
                                                                                                                                                    */
                                                                                                                                                    function processAndVisualizeTLE(rawText) {
                                                                                                                                                        // 1. Split the text into individual TLE lines
                                                                                                                                                            const lines = rawText.trim().split('\n');
                                                                                                                                                                
                                                                                                                                                                    let tleLine1 = null;
                                                                                                                                                                        let tleLine2 = null;
                                                                                                                                                                            let issName = null;

                                                                                                                                                                                // 2. Find the TLE for the ISS (NORAD ID 25544)
                                                                                                                                                                                    for (let i = 0; i < lines.length; i++) {
                                                                                                                                                                                            if (lines[i].includes('ISS (ZARYA)')) {
                                                                                                                                                                                                        // TLEs are three lines: Name (0), Line 1 (1), Line 2 (2)
                                                                                                                                                                                                                    issName = lines[i].trim();
                                                                                                                                                                                                                                tleLine1 = lines[i + 1].trim();
                                                                                                                                                                                                                                            tleLine2 = lines[i + 2].trim();
                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        if (!tleLine1 || !tleLine2) {
                                                                                                                                                                                                                                                                                statusElement.style.display = 'block';
                                                                                                                                                                                                                                                                                        statusElement.textContent = "ISS TLE data not found in the CelesTrak file.";
                                                                                                                                                                                                                                                                                                statusElement.style.color = '#ff9800';
                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    // 3. Extract the critical orbital elements (standard TLE parsing)
                                                                                                                                                                                                                                                                                                                        // TLE Format is fixed-width, so we use precise character slicing.
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                // Line 1: Epoch (Year and Day)
                                                                                                                                                                                                                                                                                                                                    // Epoch Year (e.g., '25' for 2025) is characters 18-19.
                                                                                                                                                                                                                                                                                                                                        const epochYear = parseInt(tleLine1.substring(18, 20), 10);
                                                                                                                                                                                                                                                                                                                                            // Epoch Day (e.g., '316.22557474') is characters 20-32.
                                                                                                                                                                                                                                                                                                                                                const epochDay = parseFloat(tleLine1.substring(20, 32));
                                                                                                                                                                                                                                                                                                                                                    const epoch = parseTLEEpoch(epochYear, epochDay);

                                                                                                                                                                                                                                                                                                                                                        // Line 2: Orbital Parameters
                                                                                                                                                                                                                                                                                                                                                            // Inclination [Degrees] is characters 8-16
                                                                                                                                                                                                                                                                                                                                                                const inclination = parseFloat(tleLine2.substring(8, 16));
                                                                                                                                                                                                                                                                                                                                                                    // Eccentricity (decimal assumed) is characters 26-33 (with leading '0.')
                                                                                                                                                                                                                                                                                                                                                                        const eccentricity = parseFloat('0.' + tleLine2.substring(26, 33));
                                                                                                                                                                                                                                                                                                                                                                            // Mean Motion [Revs per day] is characters 52-63
                                                                                                                                                                                                                                                                                                                                                                                const meanMotion = parseFloat(tleLine2.substring(52, 63));
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        // Update the status card
                                                                                                                                                                                                                                                                                                                                                                                            epochDateElement.textContent = epoch;
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    // 4. Prepare data for Chart.js
                                                                                                                                                                                                                                                                                                                                                                                                        const labels = ['Inclination (°)', 'Eccentricity', 'Mean Motion (revs/day)'];
                                                                                                                                                                                                                                                                                                                                                                                                            const dataPoints = [inclination.toFixed(4), eccentricity.toFixed(7), meanMotion.toFixed(7)];
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    renderChart(labels, dataPoints, issName);
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    /**
                                                                                                                                                                                                                                                                                                                                                                                                                     * Converts TLE Epoch (Year and Day of Year) to a readable date string.
                                                                                                                                                                                                                                                                                                                                                                                                                      * This is a simplified function.
                                                                                                                                                                                                                                                                                                                                                                                                                       */
                                                                                                                                                                                                                                                                                                                                                                                                                       function parseTLEEpoch(yearLastTwoDigits, dayOfYear) {
                                                                                                                                                                                                                                                                                                                                                                                                                           const fullYear = (yearLastTwoDigits >= 57) ? 1900 + yearLastTwoDigits : 2000 + yearLastTwoDigits;
                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                   // Create a date object for Jan 1 of that year
                                                                                                                                                                                                                                                                                                                                                                                                                                       const date = new Date(fullYear, 0); // Month is 0-indexed
                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                               // Add the days (minus one, since dayOfYear starts at 1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                   const days = Math.floor(dayOfYear - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                       date.setDate(date.getDate() + days);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Add the fractional part of the day for time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const fractionalHours = (dayOfYear - Math.floor(dayOfYear)) * 24;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       date.setHours(date.getHours() + Math.floor(fractionalHours));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return date.toUTCString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                               /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * Renders the Chart.js visualization (Radar Chart is great for parameters)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 function renderChart(labels, data, satelliteName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const ctx = document.getElementById('issChart').getContext('2d');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             new Chart(ctx, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type: 'radar', // A Radar Chart is great for comparing multiple parameters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         labels: labels,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     datasets: [{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     label: satelliteName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     data: data,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     backgroundColor: 'rgba(76, 175, 80, 0.4)', // Space green
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     borderColor: 'rgba(76, 175, 80, 1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     pointBackgroundColor: 'rgba(76, 175, 80, 1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     borderWidth: 2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 options: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             responsive: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         maintainAspectRatio: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     scales: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     r: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         grid: { color: 'rgba(255, 255, 255, 0.2)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             angleLines: { color: 'rgba(255, 255, 255, 0.2)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 pointLabels: { color: '#e4e4e4', font: { size: 14 } },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ticks: { display: false } // Hide value ticks for cleaner look
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             plugins: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             legend: { 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 labels: { color: '#e4e4e4' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     display: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         text: 'Key Orbital Elements',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             color: '#e4e4e4',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 font: { size: 16 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Start the process
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         fetchTLEData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         